export type AppRole = 'Admin' | 'Staff' | 'Customer';

export const PERMISSIONS = {
  ADMIN: 'ADMIN.GRANTED',
  BASIC_PUBLIC: 'BASIC.PUBLIC',
  DASHBOARD: {
    VIEW: 'DASHBOARD.VIEW',
  },
  MANAGE_USERS: {
    VIEW: 'MANAGE_USERS.VIEW',
    CREATE: 'MANAGE_USERS.CREATE',
    UPDATE: 'MANAGE_USERS.UPDATE',
    DELETE: 'MANAGE_USERS.DELETE',
  },
  MANAGE_ROOMS: {
    VIEW: 'MANAGE_ROOMS.VIEW',
    CREATE: 'MANAGE_ROOMS.CREATE',
    UPDATE: 'MANAGE_ROOMS.UPDATE',
    DELETE: 'MANAGE_ROOMS.DELETE',
  },
  MANAGE_ROOM_TYPES: {
    VIEW: 'MANAGE_ROOM_TYPES.VIEW',
    CREATE: 'MANAGE_ROOM_TYPES.CREATE',
    UPDATE: 'MANAGE_ROOM_TYPES.UPDATE',
    DELETE: 'MANAGE_ROOM_TYPES.DELETE',
  },
  MANAGE_SERVICES: {
    VIEW: 'MANAGE_SERVICES.VIEW',
    CREATE: 'MANAGE_SERVICES.CREATE',
    UPDATE: 'MANAGE_SERVICES.UPDATE',
    DELETE: 'MANAGE_SERVICES.DELETE',
  },
  MANAGE_BOOKINGS: {
    VIEW: 'MANAGE_BOOKINGS.VIEW',
    CREATE: 'MANAGE_BOOKINGS.CREATE',
    UPDATE: 'MANAGE_BOOKINGS.UPDATE',
    DELETE: 'MANAGE_BOOKINGS.DELETE',
    CHECK_IN: 'MANAGE_BOOKINGS.CHECK_IN',
    CHECK_OUT: 'MANAGE_BOOKINGS.CHECK_OUT',
  },
  MANAGE_FINANCE: {
    VIEW: 'MANAGE_FINANCE.VIEW',
    EXPORT: 'MANAGE_FINANCE.EXPORT',
  },
  MANAGE_REVIEWS: {
    VIEW: 'MANAGE_REVIEWS.VIEW',
    DELETE: 'MANAGE_REVIEWS.DELETE',
  },
  REPORTS: {
    VIEW: 'REPORTS.VIEW',
  },
  SYSTEM: {
    LOGS: 'SYSTEM.LOGS',
    SETTINGS: 'SYSTEM.SETTINGS',
  },
} as const;

export type PermissionType = string;

export const ROLE_PERMISSIONS: Record<AppRole, PermissionType[]> = {
  Admin: [PERMISSIONS.ADMIN], // Special case for Admin: has everything
  Staff: [
    PERMISSIONS.DASHBOARD.VIEW,
    PERMISSIONS.MANAGE_ROOMS.VIEW,
    PERMISSIONS.MANAGE_ROOMS.UPDATE,
    PERMISSIONS.MANAGE_ROOM_TYPES.VIEW,
    PERMISSIONS.MANAGE_SERVICES.VIEW,
    PERMISSIONS.MANAGE_BOOKINGS.VIEW,
    PERMISSIONS.MANAGE_BOOKINGS.CREATE,
    PERMISSIONS.MANAGE_BOOKINGS.UPDATE,
    PERMISSIONS.MANAGE_BOOKINGS.CHECK_IN,
    PERMISSIONS.MANAGE_BOOKINGS.CHECK_OUT,
    PERMISSIONS.MANAGE_REVIEWS.VIEW,
    PERMISSIONS.REPORTS.VIEW,
  ],
  Customer: [
    PERMISSIONS.BASIC_PUBLIC,
    PERMISSIONS.MANAGE_BOOKINGS.VIEW, // Own bookings
  ],
};
